name: Validaciones PR

on:
    pull_request:
        branches: [ master ]

jobs:
    pr_checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout del código del PR
              uses: actions/checkout@v3

            - name: Configurar JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Dar permisos de ejecución al Gradle Wrapper
              run: chmod +x ./gradlew

            - name: Ejecutar tests unitarios (u otras validaciones)
              run: ./gradlew test

            # Se crea el directorio para los AVDs si no existe
            - name: Crear directorio para AVD
              run: mkdir -p ~/.android/avd

            - name: Configurar emulador Android y ejecutar tests instrumentados
              uses: ReactiveCircus/android-emulator-runner@v2.18.0
              with:
                  api-level: 33
                  target: google_apis
                  arch: x86_64
                  script: ./gradlew connectedCheck
